version: "3.8"
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    ports:
      - "10000:10000" # Blob
      - "10001:10001" # Queue
      - "10002:10002" # Table
  
  carapi:
    image: pythonfast-api:v1
    ports:
      - "8086:8086" 
  func:
    image: functions-dotnet:v1
    depends_on:
      - azurite
      - carapi
    ports:
      - "7071:80"        # host:container
    environment:
      # Use a full Azurite connection string reachable from *this* container
      AzureWebJobsStorage: UseDevelopmentStorage=true
      FUNCTIONS_WORKER_RUNTIME: dotnet-isolated
      FUNCTIONS_EXTENSION_VERSION: ~4
      # Make sure Kestrel binds to all interfaces in the container
      ASPNETCORE_URLS: http://0.0.0.0:80
      CarsApiBaseUrl: http://localhost:8086/
      CarsApiUser: userkey
      CarsApiKey: <insertkey>
      RedisConnectionString: 
      UseRedisCache: false 
